#############################################################################
# Makefile for building: Qt
# Generated by qmake (3.1) (Qt 5.15.15)
# Project:  Qt.pro
# Template: subdirs
# Command: C:\Qt\5.15.15\bin\qmake.exe -o Makefile Qt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\5.15.15\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.15.15\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.15.15\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    = 



Makefile: Qt.pro C:/Qt/5.15.15/mkspecs/win32-g++/qmake.conf C:/Qt/5.15.15/mkspecs/features/spec_pre.prf \
		C:/Qt/5.15.15/mkspecs/qdevice.pri \
		C:/Qt/5.15.15/mkspecs/features/device_config.prf \
		C:/Qt/5.15.15/mkspecs/common/sanitize.conf \
		C:/Qt/5.15.15/mkspecs/common/gcc-base.conf \
		C:/Qt/5.15.15/mkspecs/common/g++-base.conf \
		C:/Qt/5.15.15/mkspecs/common/angle.conf \
		C:/Qt/5.15.15/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/5.15.15/mkspecs/common/windows-vulkan.conf \
		C:/Qt/5.15.15/mkspecs/common/g++-win32.conf \
		C:/Qt/5.15.15/mkspecs/common/windows-desktop.conf \
		C:/Qt/5.15.15/mkspecs/qconfig.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_ext_pcre2.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qdirect2d.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qicns.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qjpeg.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qminimal.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtga.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtiff.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwbmp.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwindows.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		C:/Qt/5.15.15/mkspecs/features/qt_functions.prf \
		C:/Qt/5.15.15/mkspecs/features/qt_config.prf \
		C:/Qt/5.15.15/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.15.15/mkspecs/features/spec_post.prf \
		C:/Qt/5.15.15/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.15.15/mkspecs/features/toolchain.prf \
		C:/Qt/5.15.15/mkspecs/features/default_pre.prf \
		C:/Qt/5.15.15/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.15.15/mkspecs/features/resolve_config.prf \
		C:/Qt/5.15.15/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.15.15/mkspecs/features/default_post.prf \
		C:/Qt/5.15.15/mkspecs/features/precompile_header.prf \
		C:/Qt/5.15.15/mkspecs/features/warn_on.prf \
		C:/Qt/5.15.15/mkspecs/features/qmake_use.prf \
		C:/Qt/5.15.15/mkspecs/features/file_copies.prf \
		C:/Qt/5.15.15/mkspecs/features/win32/windows.prf \
		C:/Qt/5.15.15/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.15.15/mkspecs/features/exceptions.prf \
		C:/Qt/5.15.15/mkspecs/features/yacc.prf \
		C:/Qt/5.15.15/mkspecs/features/lex.prf \
		Qt.pro
	$(QMAKE) -o Makefile Qt.pro
C:/Qt/5.15.15/mkspecs/features/spec_pre.prf:
C:/Qt/5.15.15/mkspecs/qdevice.pri:
C:/Qt/5.15.15/mkspecs/features/device_config.prf:
C:/Qt/5.15.15/mkspecs/common/sanitize.conf:
C:/Qt/5.15.15/mkspecs/common/gcc-base.conf:
C:/Qt/5.15.15/mkspecs/common/g++-base.conf:
C:/Qt/5.15.15/mkspecs/common/angle.conf:
C:/Qt/5.15.15/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/5.15.15/mkspecs/common/windows-vulkan.conf:
C:/Qt/5.15.15/mkspecs/common/g++-win32.conf:
C:/Qt/5.15.15/mkspecs/common/windows-desktop.conf:
C:/Qt/5.15.15/mkspecs/qconfig.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_ext_pcre2.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_core.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_network.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qdirect2d.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qgenericbearer.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qicns.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qjpeg.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qminimal.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtga.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtiff.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwbmp.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwindows.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
C:/Qt/5.15.15/mkspecs/features/qt_functions.prf:
C:/Qt/5.15.15/mkspecs/features/qt_config.prf:
C:/Qt/5.15.15/mkspecs/win32-g++/qmake.conf:
C:/Qt/5.15.15/mkspecs/features/spec_post.prf:
C:/Qt/5.15.15/mkspecs/features/exclusive_builds.prf:
C:/Qt/5.15.15/mkspecs/features/toolchain.prf:
C:/Qt/5.15.15/mkspecs/features/default_pre.prf:
C:/Qt/5.15.15/mkspecs/features/win32/default_pre.prf:
C:/Qt/5.15.15/mkspecs/features/resolve_config.prf:
C:/Qt/5.15.15/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/5.15.15/mkspecs/features/default_post.prf:
C:/Qt/5.15.15/mkspecs/features/precompile_header.prf:
C:/Qt/5.15.15/mkspecs/features/warn_on.prf:
C:/Qt/5.15.15/mkspecs/features/qmake_use.prf:
C:/Qt/5.15.15/mkspecs/features/file_copies.prf:
C:/Qt/5.15.15/mkspecs/features/win32/windows.prf:
C:/Qt/5.15.15/mkspecs/features/testcase_targets.prf:
C:/Qt/5.15.15/mkspecs/features/exceptions.prf:
C:/Qt/5.15.15/mkspecs/features/yacc.prf:
C:/Qt/5.15.15/mkspecs/features/lex.prf:
Qt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Qt.pro

qmake_all: FORCE

make_first:  FORCE
all:  FORCE
clean:  FORCE
distclean:  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: FORCE
uninstall_subtargets: FORCE

debug:

release:

check:

benchmark:
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

